# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'iba' do
	pod "LFHeatMap"
        pod 'MBProgressHUD', '~> 0.9.1'
        pod "AFNetworking", "~> 2.0"
end

target 'ibaTests' do

end

